name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      directory-client: ./client
      directory-server: ./server

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    # Run CI for Client
    - run: npm ci
      working-directory: ${{ env.directory-client }}
    - run: npm run build --if-present
      working-directory: ${{ env.directory-client }}
    - run: npm test
      working-directory: ${{ env.directory-client }}
      env:
        CI: true

    # Run CI for Server
    - run: npm ci
      working-directory: ${{ env.directory-server }}
    - run: npm run build --if-present
      working-directory: ${{ env.directory-server }}
    - run: npm test
      working-directory: ${{ env.directory-server }}
      env:
        CI: true
